version: '3'

services:
  nginx:
    build: ./nginx
    container_name: "laravel-nginx"
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/logrotate.d/nginx:/etc/logrotate.d/nginx
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - db
  php:
    build: ./php
    container_name: "laravel-php"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.3
    container_name: "laravel-mariadb"
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      TZ: "Asia/Tokyo"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init.d:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASS}
    depends_on:
      - db
    ports:
      - "8000:80"
